import type { Metadata } from "next";
import { Poppins } from "next/font/google";
// import { ThemeProvider } from "@/providers/theme-provider";
import "./globals.css";

const poppins = Poppins({
	weight: "400",
	style: "normal",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body className={`${poppins.className} antialiased`} suppressHydrationWarning>
				{/*<ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >*/}
				{children}
				{/*</ThemeProvider>*/}
			</body>
		</html>
	);
}
